Challenge/cristian bars git
SkylabCoders/skylab-bootcamp-202104-bcn pull request #11
Opened 2021-04-06 09:33 UTC by cristian-bars

Add branch Cristian Bars of precurse

2021-04-07 09:45 UTC, annasm07 reviewed
variables i espacios! lo demas genial (de lo que se jajaj)

2021-04-07 09:45 UTC, annasm07 commented on cristian-bars/Precurso/Calculadora/calculator-pro.js
> +
elimina espacio

2021-04-07 09:45 UTC, annasm07 commented on cristian-bars/Precurso/Calculadora/calculator.js
> +let resultado;
declarar al principio :)

2021-04-07 09:45 UTC, annasm07 commented on cristian-bars/Precurso/Calculadora_HTML/script/script.js
> +    //result.textContent = result.textContent;
una funcion vacia?

2021-04-07 09:45 UTC, annasm07 commented on cristian-bars/Precurso/Pasapalabra/pasapalabra.js
> +
espacios :)

2021-04-07 09:45 UTC, annasm07 commented on cristian-bars/Precurso/Pasapalabra/pasapalabra.js
> +
espacios :)

2021-04-07 09:45 UTC, annasm07 commented on cristian-bars/Precurso/Pasapalabra/pasapalabra.js
> +    let yourName = prompt("Por favor, indicanos tu nombre");
si la declaras dentro de la funcion, te funciona la variable yourName cuando la llamas fuera? he buscado esto en google: 

https://www.google.com/search?client=safari&rls=en&q=if+a+declare+a+var+inside+a+function,+can+i+call+it+outside%3F&ie=UTF-8&oe=UTF-8

2021-04-07 09:45 UTC, annasm07 commented on cristian-bars/Precurso/Pasapalabra/pasapalabra.js
> +
espacios :)

2021-04-07 09:45 UTC, annasm07 commented on cristian-bars/Precurso/Pasapalabra/pasapalabra.js
> +let questions = [
variables al principio! 😄

2021-04-07 09:45 UTC, annasm07 commented on cristian-bars/Precurso/Pasapalabra_HTML/index.html
> +
solo un espacio!

2021-04-07 09:45 UTC, annasm07 commented on cristian-bars/Precurso/Pasapalabra_HTML/index.html
> +
solo un espacio

2021-04-07 09:45 UTC, annasm07 commented on cristian-bars/Precurso/Pasapalabra_HTML/index.html
> +
lo mismo aqui 😇 un espacio solo

2021-04-07 09:45 UTC, annasm07 commented on cristian-bars/Precurso/Pasapalabra_HTML/script/pasapalabra.js
> +
espacios! quedas avisado 😝

2021-04-07 09:45 UTC, annasm07 commented on cristian-bars/Precurso/Pasapalabra_HTML/script/pasapalabra.js
> +    //Preparamos la pantalla para iniciar el juego
no se muy bien pero creo que esta funcion es un poco larga! Not sure

2021-04-07 09:45 UTC, annasm07 commented on cristian-bars/Precurso/Pasapalabra_HTML/script/pasapalabra.js
> +    let string = document.getElementById("palabra");
creo que esta funcion también es demasiado larga

2021-04-07 09:45 UTC, annasm07 commented on cristian-bars/Precurso/Pasapalabra_HTML/script/pasapalabra.js
> +        document.getElementById("boton").disabled = true;
ten cuidado con esto. En la linea 18 ya has llamado a este "boton" si declaras una variable:
const buttonSelector = document.getElementById("boton");
luego no hace falta que la llames cada vez con el document sino que puedes llamar la variable buttonSelector. No se si sirve para todos los casos pero en algunos seguro que te va a ahorrar caracteres!

2021-04-07 09:45 UTC, annasm07 commented on cristian-bars/Precurso/Pasapalabra_HTML/script/pasapalabra.js
> +
espacios

2021-04-07 09:45 UTC, annasm07 commented on cristian-bars/Precurso/Pasapalabra_HTML/script/pasapalabra.js
> +let inter;
declarar variables al principio

2021-04-07 09:45 UTC, annasm07 commented on cristian-bars/Precurso/Pasapalabra_HTML/script/pasapalabra.js
> +let puntua;
declarar las variables al principio

2021-04-07 09:45 UTC, annasm07 commented on cristian-bars/Precurso/airlines/airlines-pro.js
> +    debugger
quitar debugger :)

2021-04-07 09:45 UTC, annasm07 commented on cristian-bars/Precurso/airlines/airlines-pro.js
> +
espacios :)

2021-04-07 09:45 UTC, annasm07 commented on cristian-bars/Precurso/airlines/airlines-pro.js
> +let count;
al principio jejej!

2021-04-07 09:45 UTC, annasm07 commented on cristian-bars/Precurso/bingo/bingo.js
> +let players = [];
variables al principio

2021-04-08 07:11 UTC, NilRivera requested changes
You commited some files from Laura

2021-04-08 07:53 UTC, closed without merging