Challenge/anna sala/maria lunarillos
SkylabCoders/skylab-bootcamp-202104-bcn pull request #117
Opened 2021-04-11 08:27 UTC by annasm07

Maria lunarillos header challenge request to merge

2021-04-12 14:10 UTC, annasm07 commented
Esto es solo el Header de Lunarillos

2021-04-13 09:57 UTC, edalandete requested changes
Hola, estás subiendo tu CV también en los commits.

2021-04-14 08:01 UTC, annasm07 commented
@edalandete si, hicimos el header y el curriculum css como challenge el mismo dia por eso estan subiendo los dos a la vez. quieres que lo haga en dos ramas?

2021-04-14 08:11 UTC, edalandete commented
> @edalandete si, hicimos el header y el curriculum css como challenge el mismo dia por eso estan subiendo los dos a la vez. quieres que lo haga en dos ramas?

Entiendo, entonces OK

2021-04-14 08:12 UTC, edalandete approved these changes

2021-04-14 08:55 UTC, gteixi approved these changes
Great job Anna!!

2021-04-14 11:28 UTC, jasuarez21 approved these changes
buen trabajo, es mejor que un rafa nadal vs federer

2021-04-15 07:20 UTC, cristian-bars approved these changes
Buen trabajo Anna!

2021-04-15 07:48 UTC, merged