challenge/isabel gomez marialunarillos
SkylabCoders/skylab-bootcamp-202104-bcn pull request #119
Opened 2021-04-11 08:49 UTC by IsabelGomez87

2021-04-13 13:03 UTC, edalandete submitted a review, later dismissed
Grandioso trabajo. Increíble. 

Vigila que estás subiendo el .gitIgnore.

2021-04-14 11:24 UTC, jasuarez21 approved these changes
ISABEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEL!

2021-04-15 07:22 UTC, cristian-bars submitted a review, later dismissed
Buen trabajo Isabel!

2021-04-15 09:23 UTC, IrenePerezAlonso submitted a review, later dismissed

2021-04-16 08:27 UTC, annasm07 requested changes
Cuidado estas cambiando 319 archivos! 😱

2021-04-16 13:47 UTC, closed without merging