challenge/isabel gomez rakuten
SkylabCoders/skylab-bootcamp-202104-bcn pull request #126
Opened 2021-04-12 06:59 UTC by IsabelGomez87

2021-04-12 07:07 UTC, gteixi approved these changes
veo que habeis hecho commits de diferentes parte del codigo en equipo. muy bien!!!!

2021-04-12 07:20 UTC, edalandete approved these changes
Muy buen trabajo.

2021-04-12 07:44 UTC, edalandete requested changes
Tenemos que finalizar rakuten.

2021-04-14 07:46 UTC, jasuarez21 approved these changes
buen trabajo!

2021-04-14 12:39 UTC, IrenePerezAlonso approved these changes

2021-04-14 12:40 UTC, gteixi approved these changes
Buen trabajo Isabel!

2021-04-14 12:48 UTC, IsabelGomez87 commented
> Tenemos que finalizar rakuten.

@edalandete puedes aprobarmelo? ya esta finalizado

2021-04-14 12:51 UTC, SantiagoMC52 commented on Isabel-Gomez/challenge/rakuten/index.html
> +                <li class="mini-link"><a href="#"><span>c</span>olítica de privacidad y cookies</a></li>
Veo que en varia partes del fichero has puesto <span> para una sola letra dentro de un mismo <span>, tal que así: <span class="faqs-title"><span>m</span>ás formas de pago</span>. No sé si lo has hecho por algún motivo en concreto, en ese caso bien, sino se podría cambiar. 
Un pequeño error que si que he visto es que has escrito <span>c</span>olítica, entiendo que sería <span>p</span>olítica, para que ponga política. 
¡Buen trabajo!

2021-04-14 15:22 UTC, annasm07 reviewed
Tenemos que ver con Lluis i gilberto el tema del .DS_Store antes de subirlo :) cuando resolvamos eso te apruevo! lo demás esta genial! ☺️

2021-04-15 07:46 UTC, IsabelGomez87 commented on Isabel-Gomez/challenge/rakuten/index.html
> +                <li class="mini-link"><a href="#"><span>c</span>olítica de privacidad y cookies</a></li>
Corregido!

2021-04-15 07:53 UTC, gteixi approved these changes

2021-04-15 08:56 UTC, gteixi commented on Isabel-Gomez/challenge/rakuten/index.html
> +                <h1 class="footer-info-title"><span>r</span>akuten <span>tv</span> - tu cine en casa</h1>
te recomiendo que para mejor visibilidad del código hagas enter cada vez que cierras un tag. de tal manera que te quede:
<h1>
<span> texto span </span>
</h1>

2021-04-15 09:00 UTC, gteixi commented on Isabel-Gomez/challenge/rakuten/mixins.scss
> +@mixin flex-config($direction: row, $justify: unset, $align: unset) {
muy interesante usar el mixin con parametros, me lo guardo para usarlo en un futuro en mi código!!

2021-04-15 09:00 UTC, gteixi approved these changes

2021-04-15 09:03 UTC, gteixi commented on Isabel-Gomez/challenge/rakuten/index.html
> +    <link href="style.css" type="text/css" rel="stylesheet">
añade <link rel="shortcut icon" type="image/png" href="./../img/icono-r.png"> para poner el logo en el Titulo de la pagina web, ahora te la adjunto por el slack.

2021-04-15 09:12 UTC, gteixi approved these changes

2021-04-15 09:12 UTC, gteixi commented on Isabel-Gomez/challenge/rakuten/index.html
> +
aqui creo que tienes un espacio de mas

2021-04-15 09:12 UTC, gteixi commented on Isabel-Gomez/challenge/rakuten/index.html
> +        <nav class="nav-bar">
no se si estas usando BEM pero yo haría

- nav-bar
- nav-bar__menu
- nav-bar__menu-item--cinema

no sé si es la mejor opción pero yo lo hago así para si te sirve otra manera de trabajar.

2021-04-15 09:23 UTC, IrenePerezAlonso approved these changes

2021-04-15 21:30 UTC, gteixi submitted a review, later dismissed

2021-04-16 09:50 UTC, edalandete approved these changes

2021-04-16 09:54 UTC, edalandete submitted a review, later dismissed

2021-04-16 09:55 UTC, IrenePerezAlonso submitted a review, later dismissed

2021-04-19 09:19 UTC, gteixi approved these changes

2021-04-19 09:49 UTC, jasuarez21 approved these changes
isabel basta!

2021-04-19 10:34 UTC, edalandete approved these changes

2021-04-19 10:58 UTC, shd8 approved these changes
Let's try if DS_Store is merged or deleted.

2021-04-19 10:59 UTC, merged