Challenge/anna sala/rakuten tv
SkylabCoders/skylab-bootcamp-202104-bcn pull request #151
Opened 2021-04-14 07:04 UTC by annasm07

rakuten TV weekend challenge

2021-04-14 11:23 UTC, fredyzz approved these changes
Muy lindo código 👏

2021-04-14 11:29 UTC, IrenePerezAlonso approved these changes

2021-04-14 11:32 UTC, CheCabeza approved these changes

2021-04-15 07:55 UTC, edalandete requested changes
You are merging files from other people. 

Talk to you later.

2021-04-15 15:38 UTC, closed without merging