Challenge/david vazquez marialunarillos
SkylabCoders/skylab-bootcamp-202104-bcn pull request #180
Opened 2021-04-14 20:38 UTC by davzlum

2021-04-15 06:47 UTC, IrenePerezAlonso approved these changes

2021-04-15 07:29 UTC, IrenePerezAlonso approved these changes

2021-04-15 08:06 UTC, blopez-dev commented on david-vazquez/challenges/marialunarillos/styles/index.css
> +  font-size: 12px;
El font family por defecto, cuando lo establecemos en el body como propiedad general, lo debemos igualar a 16px.

2021-04-15 08:09 UTC, blopez-dev commented on david-vazquez/challenges/marialunarillos/styles/index.css
> +}
A nivel general y como tips, las propiedades en css deberiían escribirse en el siguiente orden:
position
display
margin
padding
font-size...(todo lo referido a estilo de fuentes)
background
.... lo que necesitemos

2021-04-15 08:12 UTC, blopez-dev submitted a review, later dismissed
Te he puesto algunos tips de css y algunas recomendaciones para mejorar.

2021-04-15 08:20 UTC, edalandete requested changes

2021-04-15 08:20 UTC, edalandete commented on david-vazquez/challenges/marialunarillos/html/index.html
> +<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossor
La identación no es la correcta.

2021-04-15 08:20 UTC, edalandete commented on david-vazquez/challenges/marialunarillos/html/index.html
> +            <li class="shop-container">
Esto debería ser un li para el icono del carrito y otro para el contadr de items. 

La clase shop-container debería ser para el ul

2021-04-15 08:20 UTC, edalandete commented on david-vazquez/challenges/marialunarillos/html/index.html
> +              <li class="button utensilio">
Cuidado con crear una clase que se llama button porque como te dejes el (.) afectarias a todos los button de tu página.

2021-04-15 08:20 UTC, edalandete commented on david-vazquez/challenges/marialunarillos/html/index.html
> +
Cuidado con los espacios de más.

2021-04-15 08:20 UTC, edalandete commented on david-vazquez/challenges/marialunarillos/html/index.html
> +
Espacios de más

2021-04-15 08:20 UTC, edalandete commented on david-vazquez/challenges/marialunarillos/html/index.html
> +
Espacios de más. 

Para evitar esto puedes configurar el prettier para que te formatee el documento html cuando se guarda.

2021-04-15 08:20 UTC, edalandete commented on david-vazquez/challenges/marialunarillos/styles/styles.scss
> +  display: flex;
puedes utilizar tu mixin de flex-configuration

2021-04-15 08:20 UTC, edalandete commented on david-vazquez/challenges/marialunarillos/styles/styles.scss
> +    flex-direction: row;
te sobra el flex-direction row.

2021-04-15 08:20 UTC, edalandete commented on david-vazquez/challenges/marialunarillos/styles/styles.scss
> +  flex-direction: row;
sobra el row

2021-04-15 08:20 UTC, edalandete commented on david-vazquez/challenges/marialunarillos/styles/styles.scss
> +  background: #ff5959;
podrías crear un mixin para cada color.

2021-04-15 08:20 UTC, edalandete commented on david-vazquez/challenges/marialunarillos/styles/styles.scss
> +  display: flex;
puedes usar el mixin de flex-configuration

2021-04-15 08:20 UTC, edalandete commented on david-vazquez/challenges/marialunarillos/styles/styles.scss
> +  flex-direction: column;
mixin de flex configuration

2021-04-15 08:20 UTC, edalandete commented on david-vazquez/challenges/marialunarillos/styles/styles.scss
> +.nav-container {
mixin de flex configuration

2021-04-15 08:20 UTC, edalandete commented on david-vazquez/challenges/marialunarillos/styles/styles.scss
> +  width: 130px;
mixin de flex configuration

2021-04-15 08:20 UTC, edalandete commented on david-vazquez/challenges/marialunarillos/styles/styles.scss
> +  float: left;
estás usando float:left.. deberías intentar usar otra cosa... display flex, flex direction row...

2021-04-16 08:48 UTC, albertmasats commented on david-vazquez/challenges/marialunarillos/styles/styles.scss
> +/*.link.news a {
Te sugiero borrar los comentarios :)

2021-04-16 08:50 UTC, davzlum commented on david-vazquez/challenges/marialunarillos/styles/index.css
> +}
En realidad tal como explico Damian, deberían ponerse en orden alfabético no?  Pregunto simplemente.

2021-04-19 09:54 UTC, IrenePerezAlonso approved these changes

2021-04-20 07:58 UTC, SantiagoMC52 approved these changes
💯

2021-04-20 08:11 UTC, cristian-bars approved these changes

2021-04-20 08:32 UTC, edalandete approved these changes

2021-04-20 08:33 UTC, merged