Challenge/chema-cabeza-array
SkylabCoders/skylab-bootcamp-202104-bcn pull request #208
Opened 2021-04-16 08:31 UTC by CheCabeza

2021-04-16 09:13 UTC, dmartorell requested changes

2021-04-16 09:13 UTC, dmartorell commented on chema-cabeza/challenge/array/src/findIndex.test.js
> +
Ojo, que aquí tienes que darle también un valor de salida -1 si no encuentra lo que busca.

2021-04-16 09:13 UTC, dmartorell commented on chema-cabeza/challenge/array/src/reduce.test.js
> +    let result = 0;
Si inicializas result a cero, cuando le pasas el callback (a,b) => a * b devuelve cero.

2021-04-19 09:30 UTC, fredyzz approved these changes
Lindo código! 👏

2021-04-19 09:30 UTC, fredyzz commented on chema-cabeza/challenge/array/src/every.test.js
> +        if (cbFunc(arr[i])) {counter++}
Acá podrías evaluarlo al revés, si uno solo no cumple la condición, entonces return false. De esta forma no recorrería todo el array en los casos de que se cumple la condición de "every".

2021-04-19 09:30 UTC, fredyzz commented on chema-cabeza/challenge/array/src/every.test.js
> +            cbFunc: (num) => num === -34,
Podrías sumar un escenario donde los valores del array no sean todos números, a ver que pasa.

2021-04-19 09:30 UTC, fredyzz commented on chema-cabeza/challenge/array/src/filter.test.js
> +        if (cbFunc(arr[i])) {newArray[newArray.length] = arr[i]}
👏

2021-04-19 09:41 UTC, gteixi submitted a review, later dismissed

2021-04-20 08:09 UTC, cristian-bars submitted a review, later dismissed
Buen trabajo Chema

2021-04-20 08:09 UTC, cristian-bars commented on chema-cabeza/challenge/array/src/filter.test.js
> +
Cuidado con los espacios en el codigo

2021-04-20 08:58 UTC, dmartorell approved these changes
Listo!

2021-04-20 08:59 UTC, gteixi approved these changes

2021-04-20 09:02 UTC, merged