Isabel gomez
SkylabCoders/skylab-bootcamp-202104-bcn pull request #22
Opened 2021-04-06 10:13 UTC by IsabelGomez87

2021-04-07 12:29 UTC, cristian-bars reviewed
Buen trabajo Isabel, la mayoria son comentarios por los espacios.

2021-04-07 12:29 UTC, cristian-bars commented on Isabel-Gomez/Precurso/Bingo/bingo.js
> +
Espacios innecesarios

2021-04-07 12:29 UTC, cristian-bars commented on Isabel-Gomez/Precurso/Bingo/bingo.js
> +
Mas espacios innecesarios ;)

2021-04-07 12:29 UTC, cristian-bars commented on Isabel-Gomez/Precurso/Bingo/bingo.js
> +
Espacios

2021-04-07 12:29 UTC, cristian-bars commented on Isabel-Gomez/Precurso/Calculadora_HTML_tema7/index.js
> +
Espacios innecessarios :D

2021-04-07 12:29 UTC, cristian-bars commented on Isabel-Gomez/Precurso/Calculadora_HTML_tema7/index.js
> +
Espacios!

2021-04-07 12:29 UTC, cristian-bars commented on Isabel-Gomez/Precurso/Calculadora_HTML_tema7/index.js
> +
Espacios

2021-04-07 12:29 UTC, cristian-bars commented on Isabel-Gomez/Precurso/Calculadora_HTML_tema7/index.js
> +
Veo otro espacio XD

2021-04-07 12:29 UTC, cristian-bars commented on Isabel-Gomez/Precurso/Calculadora_HTML_tema7/index.js
> +
Este otro doble espacio

2021-04-07 12:29 UTC, cristian-bars commented on Isabel-Gomez/Precurso/Calculadora_HTML_tema7/index.js
> +
Espacio innecesario

2021-04-07 12:29 UTC, cristian-bars commented on Isabel-Gomez/Precurso/Calculadora_HTML_tema7/index.js
> +*/
Los comentarios deben ser mas esplicitos y no tan largos

2021-04-07 12:29 UTC, cristian-bars commented on Isabel-Gomez/Precurso/Calculator/calculator_pro.js
> +*/
El codigo comentado innecesario deberia estar eliminado para tener limpio el espacio

2021-04-07 12:29 UTC, cristian-bars commented on Isabel-Gomez/Precurso/Pasapalabra/pasapalabra.js
> +
El orden deberia ser primero los let y despues los const

2021-04-08 08:14 UTC, davzlum submitted a review, later dismissed
Buen trabajo!

2021-04-08 09:01 UTC, jasuarez21 approved these changes

2021-04-08 09:04 UTC, IsabelGomez87 commented on Isabel-Gomez/Precurso/Bingo/bingo.js
> +
done

2021-04-08 09:04 UTC, IsabelGomez87 commented on Isabel-Gomez/Precurso/Bingo/bingo.js
> +
done

2021-04-08 09:05 UTC, IsabelGomez87 commented on Isabel-Gomez/Precurso/Bingo/bingo.js
> +
done

2021-04-08 09:09 UTC, davzlum commented on Isabel-Gomez/Precurso/Airlines/airlines_pro.js
> +                break;
Creo que no es correcto usar el break salvo en swift/case or while, podrías usar return para salir de la función

2021-04-08 09:09 UTC, davzlum commented on Isabel-Gomez/Precurso/Airlines/airlines_pro.js
> +                if (anotherNewFlight.toLowerCase() === 'no') break;
Lo mismo

2021-04-08 09:09 UTC, davzlum commented on Isabel-Gomez/Precurso/Bingo/bingo.js
> +
Borrar salto de línea

2021-04-08 09:09 UTC, davzlum commented on Isabel-Gomez/Precurso/Bingo/bingo.js
> +
Borrar salto de línea

2021-04-08 12:48 UTC, davzlum commented on Isabel-Gomez/Precurso/Calculadora_HTML_tema7/index.js
> +
borrar salto de línea

2021-04-08 12:49 UTC, davzlum submitted a review, later dismissed

2021-04-08 12:51 UTC, jasuarez21 approved these changes
buen trabajo es fabuloso, pareece hecho por un senior

2021-04-08 12:54 UTC, cristian-bars approved these changes
Good job Isabel!

2021-04-08 13:03 UTC, dmartorell requested changes

2021-04-08 13:03 UTC, dmartorell commented on Isabel-Gomez/Precurso/Airlines/airlines_pro.js
> +                const validsId = flights.map((flight) => flight.id);
Aquí, como solo le pasas un argumento a la función dentro de map, puedes quitarle el paréntesis. 

...map(flight => flight.id)

2021-04-08 13:03 UTC, dmartorell commented on Isabel-Gomez/Precurso/Airlines/airlines_pro.js
> +            const priceBelow = flights.filter((value) => value.cost < searchFlight);
Aquí también. Te ahorras dos caracteres 👍

2021-04-08 13:08 UTC, fredyzz commented on Isabel-Gomez/Precurso/Bingo/bingo.js
> +let bingoCard = [
Podrías hacer una función que cree un bingoCard con todos esos objetos hijos.

```suggestion

const createBingoCard = (childQuantity) => {
    let bingoCard = []
    for (let i = 0; i < childQuantity; i++) {
          bingoCard.push({ number: null, matched: false })
    }
    return bingoCard
}
```

2021-04-08 13:12 UTC, jasuarez21 approved these changes
ohh nice you are steve jobs of javascript

2021-04-08 13:15 UTC, fredyzz submitted a review, later dismissed

2021-04-08 13:30 UTC, fredyzz approved these changes

2021-04-08 13:31 UTC, jasuarez21 approved these changes
Wow! ni que tu novio fuera programador

2021-04-08 13:33 UTC, dmartorell approved these changes
Listo!

2021-04-08 13:37 UTC, IrenePerezAlonso approved these changes
Perfect!!

2021-04-08 13:38 UTC, merged