Challenge/cristian bars game of life
SkylabCoders/skylab-bootcamp-202104-bcn pull request #233
Opened 2021-04-19 09:01 UTC by cristian-bars

2021-04-19 09:25 UTC, edalandete requested changes

2021-04-19 09:25 UTC, edalandete commented on cristian-bars/challenge/game-of-life/script/script.js
> +function matrix(a,b,arrayGeneral){
Que es a? Que es b? i? j??????

Tienes que utilizar varianlrs más descriptivas

2021-04-19 09:25 UTC, edalandete commented on cristian-bars/challenge/game-of-life/script/script.js
> +function check(a, b, arrayGame, exitArray){
check de que???

2021-04-19 09:25 UTC, edalandete commented on cristian-bars/challenge/game-of-life/script/script.js
> +    cont = 0;
cont? te falta el let delante. 

Ya que estás contando neigbhours, cambia el nombre a la variable.

2021-04-19 09:25 UTC, edalandete commented on cristian-bars/challenge/game-of-life/script/script.js
> +    return cont;
me gustaria que le echaras un ojo a la función general. si la lees no se entiende mucho que estas haciendo realmente.

Cuando haces un if dentro de un if... podrias meter la expresión del segundo if dentro de la primera.

2021-04-20 08:01 UTC, shd8 approved these changes
You have little changes to do. I suggest you to start using array functions.

The syntax is: const nameOfYourFunction = (param1, param2) => { ... }

2021-04-20 08:12 UTC, edalandete approved these changes

2021-04-20 08:16 UTC, annasm07 approved these changes
nicee

2021-04-20 08:16 UTC, annasm07 commented on cristian-bars/challenge/game-of-life/source/game.test.js
> +        { array: [[0,0,0,0,0],[0,1,1,0,0],[0,1,0,1,0],[0,0,1,0,0],[0,0,0,0,0]], result: [[0,0,0,0,0],[0,1,1,0,0],[0,1,0,1,0],[0,0,1,0,0],[0,0,0,0,0]]},
testejat i toot 💪🏽👏🏼👏🏼

2021-04-20 09:02 UTC, jasuarez21 approved these changes

2021-04-20 09:02 UTC, merged