Challenge/albert masats game of life
SkylabCoders/skylab-bootcamp-202104-bcn pull request #239
Opened 2021-04-19 09:19 UTC by albertmasats

2021-04-19 09:24 UTC, cristian-bars approved these changes

2021-04-19 09:31 UTC, HosniMaRu submitted a review, later dismissed

2021-04-19 09:36 UTC, edalandete requested changes

2021-04-19 09:36 UTC, edalandete commented on albert-masats/challenge/game-of-life/gameoflife.js
> +
cuidado con los espacios dentro de las funciones

2021-04-19 09:36 UTC, edalandete commented on albert-masats/challenge/game-of-life/gameoflife.js
> +    return grid
te falta un ;

2021-04-19 09:36 UTC, edalandete commented on albert-masats/challenge/game-of-life/gameoflife.js
> +        count++
ya que cuentas vecinos, cambia el nombre de la variable por algo mas descriptivo.

2021-04-19 09:36 UTC, edalandete commented on albert-masats/challenge/game-of-life/gameoflife.js
> +    if (arrayGameOfLife[j+1] && arrayGameOfLife[i][j+1]  === 1) {
arrayGameOfLife[i][j+1]  === 1

Esta comprovacion de === 1 la haces mucho. 

Esto puede ser una funcion de 

isAlive (cell) => cell === 1

2021-04-19 10:17 UTC, davzlum requested changes

2021-04-19 10:17 UTC, davzlum commented on albert-masats/challenge/game-of-life/gameoflife.js
> +function gol () {
Nombre más descriptivo de la función. Gol, aunque sean las siglas, parece que sea una función para hacer algo de futbol xD
Podrías poner algo tipo checkCells o lo que haga la función.

2021-04-19 10:17 UTC, davzlum commented on albert-masats/challenge/game-of-life/gameoflife.js
> +let grid2 = createGrid(5, 5);
Grid2? tienes un grid1?
Ya se que si lo borraste, por eso deberías actualizar este como grid solo

2021-04-19 10:17 UTC, davzlum commented on albert-masats/challenge/game-of-life/gameoflife.js
> +            checkneighbours(i,j);
checkNeighbours, te falta la 'N' mayúscula

2021-04-19 10:17 UTC, davzlum commented on albert-masats/challenge/game-of-life/gameoflife.js
> +    setInterval(
Podrías colocarlo en una sola línea ;)

2021-04-19 10:31 UTC, albertmasats commented on albert-masats/challenge/game-of-life/gameoflife.js
> +let grid2 = createGrid(5, 5);
Corregido

2021-04-19 10:35 UTC, albertmasats commented on albert-masats/challenge/game-of-life/gameoflife.js
> +function gol () {
Corregido.

2021-04-19 10:38 UTC, albertmasats commented on albert-masats/challenge/game-of-life/gameoflife.js
> +
Corregido.

2021-04-19 10:38 UTC, albertmasats commented on albert-masats/challenge/game-of-life/gameoflife.js
> +    return grid
Corregido.

2021-04-19 10:39 UTC, albertmasats commented on albert-masats/challenge/game-of-life/gameoflife.js
> +        count++
Corregido.

2021-04-19 10:39 UTC, albertmasats commented on albert-masats/challenge/game-of-life/gameoflife.js
> +let grid2 = createGrid(5, 5);
Corregido.

2021-04-19 10:39 UTC, albertmasats commented on albert-masats/challenge/game-of-life/gameoflife.js
> +            checkneighbours(i,j);
Corregido.

2021-04-19 10:41 UTC, albertmasats commented on albert-masats/challenge/game-of-life/gameoflife.js
> +    setInterval(
Corregido.

2021-04-19 11:02 UTC, cristian-bars approved these changes
Buen trabajo Albert!

2021-04-19 11:04 UTC, edalandete approved these changes

2021-04-19 13:01 UTC, HosniMaRu approved these changes

2021-04-19 21:03 UTC, HosniMaRu approved these changes

2021-04-20 07:56 UTC, IsabelGomez87 approved these changes

2021-04-20 07:58 UTC, jasuarez21 approved these changes

2021-04-20 08:07 UTC, Laura-SM approved these changes
Good job!

2021-04-20 09:11 UTC, davzlum approved these changes

2021-04-20 09:11 UTC, merged