Challenge/chema cabeza strictequals
SkylabCoders/skylab-bootcamp-202104-bcn pull request #241
Opened 2021-04-19 09:31 UTC by CheCabeza

2021-04-19 09:36 UTC, dmartorell requested changes
Chema! string-string me da falso!

2021-04-19 10:11 UTC, IrenePerezAlonso approved these changes

2021-04-19 10:38 UTC, Laura-SM submitted a review, later dismissed
Equals strings don't work.

2021-04-19 10:54 UTC, davzlum approved these changes

2021-04-19 10:55 UTC, davzlum commented
> Chema! string-string me da falso!

Está bien, en el ejercicio se pedía que devolviese 'false'.

2021-04-20 07:57 UTC, jasuarez21 submitted a review, later dismissed

2021-04-20 08:06 UTC, gaxxrodri submitted a review, later dismissed

2021-04-20 08:25 UTC, IrenePerezAlonso approved these changes

2021-04-20 08:26 UTC, jasuarez21 approved these changes

2021-04-20 08:50 UTC, Laura-SM approved these changes
Good job!

2021-04-20 08:54 UTC, dmartorell approved these changes
Perfect!

2021-04-20 08:55 UTC, merged