Challenge/laura game of life
SkylabCoders/skylab-bootcamp-202104-bcn pull request #246
Opened 2021-04-19 09:53 UTC by Laura-SM

Testing is not finished...

2021-04-19 09:56 UTC, IrenePerezAlonso approved these changes
TREMENDO!!! Eres una máquina!!!

2021-04-19 09:57 UTC, jasuarez21 approved these changes
bon treball laura!

2021-04-19 09:57 UTC, jasuarez21 commented on laura-sabater/challenges/game-of-life/game-of-life.test.js
> +        // Act
intenta no pujar comentaris a las pull request

2021-04-19 09:57 UTC, jasuarez21 commented on laura-sabater/challenges/game-of-life/styles/game-of-life.scss
> +#environment {
intenta no treballar amb ids

2021-04-19 10:15 UTC, edalandete requested changes

2021-04-19 10:15 UTC, edalandete commented on laura-sabater/challenges/game-of-life/game-of-life.js
> +      const spot = document.createElement("td");
podrías cambiar la variable a "td" ya que lo que estas creando son td, al poner spot me ha parecido rari

2021-04-19 10:15 UTC, edalandete commented on laura-sabater/challenges/game-of-life/game-of-life.js
> +  if (matrix[rowPosition][colPosition] === 1) {
El isCellAlive podrias hacer que te devolviera directamente el:

return matrix[rowPosition][colPosition] === 1; 

Si es cierto te devuelve true, si es falso te devuelve false.

2021-04-19 10:15 UTC, edalandete commented on laura-sabater/challenges/game-of-life/game-of-life.js
> +  let aliveCell = isCellAlive(matrix, rowPosition, colPosition);
podrias hacer que directamente le pasaras la celda: 

isCellAlive(matrix[rowPosition][colPosition]) y solo le pasas 1 parametro que es la celda.

2021-04-19 10:15 UTC, edalandete commented on laura-sabater/challenges/game-of-life/game-of-life.js
> +  let aliveNeighbours = neighbours.filter((cell) => cell === 1);
si cambias la función isCellAlive tal y como te he dicho, puedes reutilizarla aqui:

neighbours.filter((cell) => isCellAlive(cell));

2021-04-19 10:40 UTC, davzlum approved these changes
Muy buen trabajo Laura! Utilizando las arrow functions, testeando las funciones, haciendo funciones pequeñas.. Good job!

2021-04-20 07:52 UTC, shd8 approved these changes
Good job! Merge it ;)

2021-04-20 07:58 UTC, Laura-SM commented
Thanks for the comments!

2021-04-20 08:08 UTC, edalandete approved these changes

2021-04-20 08:10 UTC, merged