add heroes(no finished)
SkylabCoders/skylab-bootcamp-202104-bcn pull request #264
Opened 2021-04-20 08:19 UTC by JDSanchon

2021-04-20 08:38 UTC, IsabelGomez87 requested changes

2021-04-20 08:38 UTC, IsabelGomez87 commented on juanda-sanchon/challenge/heroes/index.html
> +    <script src="./jss/script.js"></script>
Cuidado que el script debe ir fuera del body :)

2021-04-20 08:38 UTC, IsabelGomez87 commented on juanda-sanchon/challenge/heroes/jss/script.js
> +
eliminar espacios

2021-04-20 08:50 UTC, edalandete requested changes

2021-04-20 08:50 UTC, edalandete commented on juanda-sanchon/challenge/heroes/jss/script.js
> +function createbodier(){
cudado el cammelCase

2021-04-20 08:50 UTC, edalandete commented on juanda-sanchon/challenge/heroes/jss/script.js
> +        let objList = document.createElement('li');
no seria mejor extraer la creación del enlace a una funcion que sea createLink en vez de poner ese if en el for? 

Imagina que tienes 4 enlaces.. tendrias que poner 4 if...

2021-04-27 07:38 UTC, ulldecorb approved these changes

2021-04-27 07:38 UTC, ulldecorb commented on juanda-sanchon/challenge/heroes/index.html
> +    <title>Document</title>
Cambia el título de la pagina web por algo descriptivo. Por ejemplo cambiar 'Document' por 'Heroes'.

2021-04-27 07:38 UTC, ulldecorb commented on juanda-sanchon/challenge/heroes/jss/script.js
> +let body = document.querySelector('body');
Si la variable es solo de lectura utiliza 'const' en vez de 'let' para declarar la variable.
En el caso de insertar nodos de momento siempre es const.

2021-04-27 07:38 UTC, ulldecorb commented on juanda-sanchon/challenge/heroes/jss/script.js
> +    let list = document.createElement('ul');
Atento al const por let

2021-04-27 08:06 UTC, gaxxrodri approved these changes

2021-04-27 08:06 UTC, shd8 approved these changes
Merge and charge with technical debt.

2021-04-27 08:07 UTC, edalandete approved these changes

2021-04-27 08:10 UTC, closed without merging