Gaspar r
SkylabCoders/skylab-bootcamp-202104-bcn pull request #29
Opened 2021-04-06 10:31 UTC by gaxxrodri

2021-04-08 07:37 UTC, gteixi approved these changes

2021-04-08 07:39 UTC, gteixi approved these changes

2021-04-08 07:39 UTC, gteixi commented on Gaspar-R/precurso/bingo/index.html
> +
hay espacios de más, elimínalos!

2021-04-08 07:39 UTC, gteixi commented on Gaspar-R/precurso/bingo/index.html
> +
lo mismo, espacios de más

2021-04-08 07:39 UTC, gteixi commented on Gaspar-R/precurso/bingo/script/main.js
> +
espacios de más igual, eliminarlos

2021-04-08 08:18 UTC, gteixi submitted a review, later dismissed
genial, chao espacios!!!!!

2021-04-08 08:23 UTC, davzlum submitted a review, later dismissed
Good job!

2021-04-08 12:32 UTC, dmartorell requested changes
Gaspar, te he marcado algunos saltos de linea innecesarios. Hay más. Chequéalos.

2021-04-08 12:32 UTC, dmartorell commented on Gaspar-R/precurso/airline/index.html
> +    <title>Airline </title>
Ojo el espacio que dejas al final de Airline.

2021-04-08 12:32 UTC, dmartorell commented on Gaspar-R/precurso/airline/index.html
> +
Eliminar saltos de línea.

2021-04-08 12:32 UTC, dmartorell commented on Gaspar-R/precurso/airline/script/main.js
> +
Eliminar saltos de línea.

2021-04-08 12:32 UTC, dmartorell commented on Gaspar-R/precurso/airline/script/main.js
> +	}	console.log("*****************************")
Este console debe ir en la linea de abajo.

2021-04-08 12:32 UTC, dmartorell commented on Gaspar-R/precurso/airline/script/main.js
> +
Sobran saltos de linea ;)

2021-04-08 12:32 UTC, dmartorell commented on Gaspar-R/precurso/bingo/index.html
> +  <title>Bingo SkyLab </title>
Aquí tienes también un espacio después del título ¿?

2021-04-08 12:32 UTC, dmartorell commented on Gaspar-R/precurso/bingo/script/main.js
> +let card;
Creo que cuando declaras variables tienes que asignarles un valor inmediatamente.

2021-04-08 12:32 UTC, dmartorell commented on Gaspar-R/precurso/bingo/script/main.js
> +
Acá también sobran saltos de linea.

2021-04-08 12:32 UTC, dmartorell commented on Gaspar-R/precurso/bingo/script/main.js
> +	if (!username)
Después del if tendrías que meter las llaves {} aunque así también funciona.

2021-04-08 12:32 UTC, dmartorell commented on Gaspar-R/precurso/bingo/script/main.js
> +	if (caard == undefined)
Lo mismo aquí: faltan las llaves {} después del if.

2021-04-08 12:32 UTC, dmartorell commented on Gaspar-R/precurso/bingo/style/styles.css
> +
Sobra el salto de linea.

2021-04-08 12:32 UTC, dmartorell commented on Gaspar-R/precurso/calculadora/script/main.js
> +		if(isNaN(num1) || num2 !== undefined && isNaN(num2)){		//comprueba si hay 1 o 2 parametros, y si son o no números.
Creo que los comentarios tienes que colocarlos justo encima de la linea que quieres comentar, no al lado.

2021-04-08 12:32 UTC, dmartorell commented on Gaspar-R/precurso/calculadora/script/main.js
> +
Ojo con los saltos de linea :)

2021-04-08 12:32 UTC, dmartorell commented on Gaspar-R/precurso/pasapalabras/scripts/main.js
> +
Borrar saltos de linea.

2021-04-08 12:50 UTC, gaxxrodri commented on Gaspar-R/precurso/airline/script/main.js
> +	}	console.log("*****************************")
si lo pongo debajo, se me muestra en la consola incluso antes de llamar a la función. Y en este caso quiero q se muestre luego de imprimir los vuelos.

2021-04-08 15:45 UTC, dmartorell submitted a review, later dismissed
Listo!

2021-04-08 15:57 UTC, ulldecorb commented on Gaspar-R/precurso/bingo/index.html
> +
Delete empty line break between all HTML elements.

2021-04-08 15:57 UTC, ulldecorb commented on Gaspar-R/precurso/bingo/script/main.js
> +let startGameBtn = document.querySelector("#startBtn");
Variables's name for DOM selectors better with CONST. Change "let" variable declaration to "const".

2021-04-09 07:43 UTC, davzlum approved these changes

2021-04-09 07:43 UTC, dmartorell approved these changes

2021-04-09 07:43 UTC, gteixi approved these changes

2021-04-09 07:44 UTC, gteixi approved these changes

2021-04-09 08:11 UTC, ulldecorb approved these changes
Ok Job Job

2021-04-09 08:11 UTC, merged