challenge/isabel gomez pokemons
SkylabCoders/skylab-bootcamp-202104-bcn pull request #297
Opened 2021-04-22 09:36 UTC by IsabelGomez87

2021-04-22 09:41 UTC, gteixi commented on Isabel-Gomez/challenge/pokemons/assets/dashboard/dashboard.component.js
> +const createElement = (tag, parent, innerHTML, className, href) => {
Genial función! La podrías poner en el .service ya que es global y luego aquí solo llamarla para crear tus elementos.

2021-04-22 09:42 UTC, gteixi commented on Isabel-Gomez/challenge/pokemons/assets/details/details.component.js
> +const getDetails = async (id) => {
muy bien este async y await Isabeeeeeeeeeeeeeel! 🥳

2021-04-22 09:42 UTC, gteixi commented on Isabel-Gomez/challenge/pokemons/services/services.js
> +const fetchDashboardPokemons = async () => {
me tienes que explicar esto compi, esta genial!!!

2021-04-22 09:47 UTC, IrenePerezAlonso submitted a review, later dismissed

2021-04-22 09:48 UTC, gteixi submitted a review, later dismissed
Isabel, te eligo a ti!

2021-04-22 09:57 UTC, blopez-dev approved these changes

2021-04-22 09:57 UTC, blopez-dev commented on Isabel-Gomez/challenge/pokemons/assets/dashboard/dashboard.component.js
> +  });
Perfecto,!!

2021-04-22 09:57 UTC, blopez-dev commented on Isabel-Gomez/challenge/pokemons/assets/list/list.component.js
> +    }
Esto huele a ternario desde lejos...jajaj

2021-04-22 10:58 UTC, NilRivera requested changes
You should create a PR for each challenge (ToH & Pokemons)

2021-04-22 11:04 UTC, NilRivera approved these changes

2021-04-27 08:04 UTC, davzlum approved these changes

2021-04-27 08:04 UTC, IrenePerezAlonso approved these changes

2021-04-27 08:08 UTC, CheCabeza approved these changes

2021-04-27 08:09 UTC, edalandete approved these changes
Muy bien Isaaaa

2021-04-27 08:12 UTC, merged