Challenge/juanda git
SkylabCoders/skylab-bootcamp-202104-bcn pull request #39
Opened 2021-04-07 05:11 UTC by JDSanchon

2021-04-07 13:15 UTC, cristian-bars reviewed
Buen trabajo Juanda, la mayoria de cambios son por espacios!

2021-04-07 13:15 UTC, cristian-bars commented on juanda/airlines/Airline_pro_juanda.js
> +        }else if(flights[i].scale === false){
Si la comprobación solo puede ser true o false, no hace falta poner la condicion en el segundo if, tan solo poner else y borrar la parte "if(flights[i].scale === false)"

2021-04-07 13:15 UTC, cristian-bars commented on juanda/airlines/Airline_pro_juanda.js
> +
Espacios ;)

2021-04-07 13:15 UTC, cristian-bars commented on juanda/airlines/Airline_pro_juanda.js
> +                primeraSalida = false;
Las comprobaciones se pueden hacer en una funcion a parte para limpiar las funciones y no tenerlas tan llenas

2021-04-07 13:15 UTC, cristian-bars commented on juanda/airlines/Airline_pro_juanda.js
> +    debugger
Los debugger deben ser eliminados! :D

2021-04-07 13:15 UTC, cristian-bars commented on juanda/airlines/Airline_pro_juanda.js
> +}
Esta funcion es muy grande, podria dividirse para tener funciones mas pequeñas

2021-04-07 13:15 UTC, cristian-bars commented on juanda/bingo/Bingo_juanda.js
> +//mostrar Ranking de usuarios. DONDE¿? Antes de preguntar el nombre del jugador.
El codigo debes estar limpio y no estar lleno de comentarios como estos. Los comentarios deben ser muy precisos y cortos

2021-04-07 13:15 UTC, cristian-bars commented on juanda/bingo/Bingo_juanda.js
> +
Quitar espacios! XD

2021-04-07 13:15 UTC, cristian-bars commented on juanda/pasapalabra/pasapalabra_juanda.js
> +
Espacios entre lineas innecesarios! 🕺

2021-04-08 07:20 UTC, NilRivera requested changes
You had to merge/rebase after the pull. Instead, you committed all the incoming changes. Fix it

2021-04-08 07:54 UTC, JDSanchon commented on juanda/airlines/Airline_pro_juanda.js
> +
Done! Y copy/paste para los mensajes similares xD

2021-04-08 07:54 UTC, JDSanchon commented on juanda/airlines/Airline_pro_juanda.js
> +
Done! Y copy/paste para los mensajes similares xD

2021-04-08 07:54 UTC, JDSanchon commented on juanda/airlines/Airline_pro_juanda.js
> +
Done! Y copy/paste para los mensajes similares xD

2021-04-08 07:54 UTC, JDSanchon commented on juanda/airlines/Airline_pro_juanda.js
> +        }else if(flights[i].scale === false){
Toda la razón. Cambio hecho.

2021-04-08 07:55 UTC, JDSanchon commented on juanda/airlines/Airline_pro_juanda.js
> +
Done! Y copy/paste para los mensajes similares xD

2021-04-08 07:55 UTC, JDSanchon commented on juanda/airlines/Airline_pro_juanda.js
> +    debugger
:O Solucionado

2021-04-08 08:03 UTC, JDSanchon commented on juanda/bingo/Bingo_juanda.js
> +//mostrar Ranking de usuarios. DONDE¿? Antes de preguntar el nombre del jugador.
Hecho!

2021-04-08 08:21 UTC, JDSanchon commented on juanda/pasapalabra/pasapalabra_juanda.js
> +
DONE

2021-04-08 08:42 UTC, closed without merging