Challange/albert masats git
SkylabCoders/skylab-bootcamp-202104-bcn pull request #40
Opened 2021-04-07 06:59 UTC by albertmasats

2021-04-07 09:25 UTC, blopez-dev commented on albert-masats/precurso/tema1/calculator-pro.js
> +    }else if (newNumber === undefined) {
Se puede agrupar en una misma condición si, en caso de ser true, el resultado devuelto será el mismo.

2021-04-07 11:19 UTC, JDSanchon commented on albert-masats/precurso/tema1/calculator-pro.js
> +
regular los saltos de linea extra

2021-04-07 11:25 UTC, JDSanchon commented on albert-masats/precurso/tema1/calculator-pro.js
> +
evitar saltos de linea extra

2021-04-07 11:25 UTC, JDSanchon commented on albert-masats/precurso/tema1/calculator-pro.js
> +
de nuevo el tema del sato de linea

2021-04-07 11:31 UTC, JDSanchon commented on albert-masats/precurso/tema3/bingo.js
> +    let k = Math.floor(Math.random() * copiedArray.length);
Aunque solo sea algo local, es interesante que el nombre de las variables nos indique algo de lo que hace o representa.

2021-04-07 11:31 UTC, JDSanchon commented on albert-masats/precurso/tema3/bingo.js
> +            for(l=5; l<bingoCard.length -5; l++) {
Si has pasado el sonarqube ya lo habrás visto. Tenemos que iniciar la varibale del for --> for(**let** l=5; ...)

2021-04-07 11:41 UTC, shd8 commented on albert-masats/precurso/tema1/calculator-pro.js
> +
Quitar salto de línea 12. Estilo de código de equipo.

2021-04-07 11:41 UTC, shd8 commented on albert-masats/precurso/tema1/calculator-pro.js
> +
Delete line 20. Unified code style.

2021-04-07 11:41 UTC, shd8 commented on albert-masats/precurso/tema1/calculator-pro.js
> +
Delete line 29. Unified code style.

2021-04-07 11:41 UTC, shd8 commented on albert-masats/precurso/tema1/calculator-pro.js
> +
Better refactor this function. Take out the function squareRoot and call it in line 34 instead.

2021-04-07 11:41 UTC, shd8 commented on albert-masats/precurso/tema1/calculator-pro.js
> +        function sum(numberList) {    //Si hay más de un dato en el array pasa por las funciones de suma, resta, mult, div.
Better refactor this function. Take out the function sum and call it before the else instead.

2021-04-07 11:41 UTC, shd8 commented on albert-masats/precurso/tema1/calculator-pro.js
> +                for (let i=0; i< numberList.length; i++) {
For simple 'for' loops better use for..of or for..in.

2021-04-07 11:45 UTC, IrenePerezAlonso reviewed
Mírate esto!!! :)

2021-04-07 11:45 UTC, IrenePerezAlonso commented on albert-masats/precurso/tema3/bingo.js
> +const rankingArray = [];
Primero se ponen las constantes y luego todas las let, así que esta variable debería ir al principio de todas las variables :)

2021-04-07 11:45 UTC, IrenePerezAlonso commented on albert-masats/precurso/tema3/bingo.js
> +function NinetyNumbers() {     //Crea un array de 90 numeros ordenados del 1 al 90.
Cuando se hacen comentarios  después de // se deja un espacio y luego se empieza el comentario 👯

2021-04-07 11:45 UTC, IrenePerezAlonso commented on albert-masats/precurso/tema3/bingo.js
> +function pick15FromRanArray() {        //Coge numeros (no repetidos) al azar de un array de 90 numeros que se utilizarán para el cartón.
Falta el espacio antes de las // en el comentario 🐻

2021-04-07 11:45 UTC, IrenePerezAlonso commented on albert-masats/precurso/tema3/bingo.js
> +    //Primera linea
Espacio!!!!! 🌵

2021-04-07 11:45 UTC, IrenePerezAlonso commented on albert-masats/precurso/tema3/bingo.js
> +    //Segunda linea
Esssssspassssssiooooo 🐑

2021-04-07 11:45 UTC, IrenePerezAlonso commented on albert-masats/precurso/tema3/bingo.js
> +    //Tercera linea
E S P A C I O 😺

2021-04-07 11:45 UTC, IrenePerezAlonso commented on albert-masats/precurso/tema3/bingo.js
> +function bingoCardView() { //Vista para prompt
Creo que a estas alturas ya sabrás qué sucede aquí :^)))))) 🍰

2021-04-07 11:45 UTC, IrenePerezAlonso commented on albert-masats/precurso/tema3/bingo.js
> +function bingoCardConsole() {       //Vista consola
Lo mismo de siempre con el espacio jeje <3

2021-04-08 07:23 UTC, NilRivera requested changes
You deleted damian's files, then you did a commit of those deletions. Fix it please

2021-04-08 08:49 UTC, davzlum commented on albert-masats/precurso/tema2/airlines-pro.js
> +
eliminar 1 salto de linea

2021-04-08 08:49 UTC, davzlum commented on albert-masats/precurso/tema2/airlines-pro.js
> +
eliminar salto de linea

2021-04-08 08:49 UTC, davzlum commented on albert-masats/precurso/tema2/airlines-pro.js
> +
Borrar salto de línea

2021-04-08 13:22 UTC, Emerson-feral requested changes

2021-04-08 13:22 UTC, Emerson-feral commented on albert-masats/precurso/tema3/bingo.js
> +    for (i=1; i<91; i++) {
Sin let o const la variable "i" se queda como global scope

2021-04-08 17:29 UTC, ulldecorb approved these changes
Clean code can be improve.

2021-04-08 17:29 UTC, Laura-SM approved these changes
Good job Albert!

2021-04-08 17:29 UTC, ulldecorb commented on albert-masats/precurso/tema1/calculator.js
> +
Delete empty line break.

2021-04-08 21:15 UTC, shd8 approved these changes
Good changes, nice job.

2021-04-09 05:05 UTC, closed without merging