Dani Martorell / Challenge Git
SkylabCoders/skylab-bootcamp-202104-bcn pull request #42
Opened 2021-04-07 09:08 UTC by dmartorell

2021-04-07 13:14 UTC, gteixi commented on dani-martorell/challenge-git/AIRLINES-PRO/airlines-pro.js
> +  let userName;
cuando declares una variable es importante que la inicializes (aunque sea inicializarla a 0 o a un string vacio) ! 😮

2021-04-07 13:14 UTC, gteixi commented on dani-martorell/challenge-git/AIRLINES-PRO/airlines-pro.js
> +          if(!newFlight) return;
los if tienen que abrirse y cerrarse con brackets =>
if (condicion) { 
código
}

2021-04-07 13:14 UTC, gteixi commented on dani-martorell/challenge-git/AIRLINES-PRO/airlines-pro.js
> +      if(flight.stopOver) NumFlightsWithStopOver += 1;
lo mismo 😸 , este if tiene que estar con brackets!

2021-04-07 13:14 UTC, gteixi commented on dani-martorell/challenge-git/AIRLINES-PRO/airlines-pro.js
> +  let operation;
lo mismo, importante inicializar la variable a un valor!!

2021-04-07 13:14 UTC, gteixi commented on dani-martorell/challenge-git/AIRLINES-PRO/airlines-pro.js
> +    return { data: flightData, operationType: 'create' }
el contenido de un return tiene que estar entre parentesis = return(); 😋

2021-04-08 08:31 UTC, dmartorell commented on dani-martorell/challenge-git/AIRLINES-PRO/airlines-pro.js
> +  while(true){
Si lo cambio por el username === true no chuta.
Ese true me permite entrar en el loop de primeras y no abandonar hasta que se mete algo diferente a string vacío.

2021-04-08 08:35 UTC, dmartorell commented on dani-martorell/challenge-git/AIRLINES-PRO/airlines-pro.js
> +      if(userName !== '') break;
El break en while-loop permite romper el loop y seguir a la siguiente linea de código. Creo que sí se puede usar.

2021-04-08 08:41 UTC, dmartorell commented on dani-martorell/challenge-git/AIRLINES-PRO/airlines-pro.js
> +          if(!newFlight) return;
Hecho!! :)

2021-04-08 08:42 UTC, dmartorell commented on dani-martorell/challenge-git/AIRLINES-PRO/airlines-pro.js
> +        display(deletedFlight);
Hecho! ;)

2021-04-08 08:45 UTC, dmartorell commented on dani-martorell/challenge-git/AIRLINES-PRO/airlines-pro.js
> +    while(true){
Ese true me permite entrar en el loop de primeras y no abandonar hasta que se mete algo diferente a un número válido.

2021-04-08 08:45 UTC, dmartorell commented on dani-martorell/challenge-git/AIRLINES-PRO/airlines-pro.js
> +      if(+inputPrice) break;
Funciona en while loop también ;)

2021-04-08 08:46 UTC, dmartorell commented on dani-martorell/challenge-git/AIRLINES-PRO/airlines-pro.js
> +      if(+inputRange === 1 || +inputRange === 2 || +inputRange == 3) break;
No quiero abandonar la función, quiero que salte el while loop y siga leyendo código.

2021-04-08 08:47 UTC, dmartorell commented on dani-martorell/challenge-git/AIRLINES-PRO/airlines-pro.js
> +    display(coincidences);
Hecho!

2021-04-08 08:49 UTC, dmartorell commented on dani-martorell/challenge-git/AIRLINES-PRO/airlines-pro.js
> +      if(flight.stopOver) NumFlightsWithStopOver += 1;
Yes! Hecho :)

2021-04-08 08:50 UTC, gteixi approved these changes
genial!!

2021-04-08 08:52 UTC, gteixi approved these changes

2021-04-08 08:52 UTC, gteixi approved these changes

2021-04-08 08:52 UTC, gteixi submitted a review, later dismissed

2021-04-08 08:55 UTC, dmartorell commented on dani-martorell/challenge-git/AIRLINES-PRO/airlines-pro.js
> +function userIsAdmin(){
Hecho!

2021-04-08 08:57 UTC, dmartorell commented on dani-martorell/challenge-git/AIRLINES-PRO/airlines-pro.js
> +}
Hecho

2021-04-08 08:59 UTC, dmartorell commented on dani-martorell/challenge-git/AIRLINES-PRO/airlines-pro.js
> +  let operation;
Hecho! ;)

2021-04-08 08:59 UTC, dmartorell commented on dani-martorell/challenge-git/AIRLINES-PRO/airlines-pro.js
> +}
Hecho!

2021-04-08 08:59 UTC, dmartorell commented on dani-martorell/challenge-git/AIRLINES-PRO/airlines-pro.js
> +
Hecho!

2021-04-08 08:59 UTC, dmartorell commented on dani-martorell/challenge-git/AIRLINES-PRO/airlines-pro.js
> +      } else break;
Dentro del while loop se puede hacer :)

2021-04-08 09:00 UTC, dmartorell commented on dani-martorell/challenge-git/AIRLINES-PRO/airlines-pro.js
> +      } else break;
;) Funciona bien.

2021-04-08 09:01 UTC, dmartorell commented on dani-martorell/challenge-git/AIRLINES-PRO/airlines-pro.js
> +
Hecho!

2021-04-08 09:01 UTC, gteixi approved these changes

2021-04-08 09:05 UTC, gteixi approved these changes

2021-04-08 09:07 UTC, dmartorell commented on dani-martorell/challenge-git/AIRLINES-PRO/airlines-pro.js
> +    return { data: flightData, operationType: 'create' }
Funciona igual :) gracias!

2021-04-08 12:26 UTC, cristian-bars reviewed
Buen trabajo Dani

2021-04-08 12:26 UTC, cristian-bars commented on dani-martorell/challenge-git/AIRLINES/airlines.js
> +  { id: 10, to: 'Tel-Aviv', from: 'Madrid', cost: 150, stopOver: false }
Los numeros en el id tienen que ser en formato normal, sin el cero por delante, sino el sonarqube te marcara error

2021-04-08 12:26 UTC, cristian-bars commented on dani-martorell/challenge-git/PASAPALABRA-PRO/pasapalabra-pro.js
> +
Espacio innecesario

2021-04-08 13:25 UTC, edalandete commented on dani-martorell/challenge-git/AIRLINES-PRO/airlines-pro.js
> +    while(true){
Dale una vuelta al funcionamiento del método. 

Piensa que mientras no has introducido el dato correctamente, lo vas pidiendo hasta que sea un dato válido.

2021-04-08 13:33 UTC, davzlum approved these changes

2021-04-08 13:35 UTC, edalandete requested changes

2021-04-08 13:35 UTC, edalandete commented on dani-martorell/challenge-git/AIRLINES-PRO/airlines-pro.js
> +    if (hasStopOver === 'n') {
vigila que estás utulizando la misma variable y le asignas un string y luego un boolean

2021-04-08 15:49 UTC, dmartorell commented on dani-martorell/challenge-git/AIRLINES-PRO/airlines-pro.js
> +}
Ok!

2021-04-08 15:50 UTC, dmartorell commented on dani-martorell/challenge-git/AIRLINES-PRO/airlines-pro.js
> +    while(true){
Gracias, Edgar!

2021-04-08 15:52 UTC, dmartorell commented on dani-martorell/challenge-git/AIRLINES-PRO/airlines-pro.js
> +}
Hecho!

2021-04-08 15:52 UTC, dmartorell commented on dani-martorell/challenge-git/AIRLINES-PRO/airlines-pro.js
> +}
Hecho!

2021-04-08 15:53 UTC, dmartorell commented on dani-martorell/challenge-git/AIRLINES-PRO/airlines-pro.js
> +  });
Hecho

2021-04-08 16:04 UTC, cristian-bars approved these changes

2021-04-08 16:11 UTC, edalandete approved these changes

2021-04-08 16:22 UTC, gteixi approved these changes

2021-04-08 16:24 UTC, davzlum approved these changes

2021-04-08 16:25 UTC, merged