Challenge/davidvazquez
SkylabCoders/skylab-bootcamp-202104-bcn pull request #45
Opened 2021-04-07 11:38 UTC by davzlum

2021-04-07 12:14 UTC, cristian-bars commented on davidvazquez/airlines/airlines.js
> +
Suprimir espacios

2021-04-08 07:31 UTC, davzlum reviewed
Ya he hecho los cambios, y los del pull-request oculto también

2021-04-08 07:31 UTC, davzlum commented on davidvazquez/airlines/airlines.js
> +
Dit y fet! 👯

2021-04-08 09:06 UTC, cristian-bars approved these changes
Buen trabajo

2021-04-08 12:49 UTC, dmartorell requested changes

2021-04-08 12:49 UTC, dmartorell commented on davidvazquez/Precurso/airlines/airlines_pro.js
> +    let scaleCheck;
Creo que hay que asignar un valor inmediatamente después de declarar la variable.

2021-04-08 12:49 UTC, dmartorell commented on davidvazquez/Precurso/airlines/airlines_pro.js
> +    parseInt(price)
¿Dónde guardas esta transformación?

2021-04-08 12:49 UTC, dmartorell commented on davidvazquez/Precurso/airlines/airlines_pro.js
> +        return insertName();
Yo diría que es mejor que hagas un while loop en lugar de volver a llamar a la función cada vez que el nombre no pasa la validación. Por eficiencia. Creo :)

2021-04-08 12:49 UTC, dmartorell commented on davidvazquez/Precurso/airlines/airlines_pro.js
> +    for(let i of flightsList){
'i' puedes cambiar por 'index'?

2021-04-08 12:49 UTC, dmartorell commented on davidvazquez/Precurso/airlines/airlines_pro.js
> +function whoAreYou () {
Me mola el nombre de la función! :)
Pero tendría que describir lo que hace.

2021-04-08 12:49 UTC, dmartorell commented on davidvazquez/Precurso/airlines/airlines_pro.js
> +function admin() {
El nombre de esta función también tendría que ser más descriptiva.

2021-04-08 13:01 UTC, Emerson-feral commented on davidvazquez/calculadora/calculadora.js
> +      outputResults.push('La raiz cuadrada de ' + num1 + ' es igual a ' + raiz);
No es que este mal pero podrías utilizar template literals ( ${`La raiz cuadrada...` ) ) porque queda mas legible

2021-04-08 13:07 UTC, davzlum commented on davidvazquez/Precurso/airlines/airlines_pro.js
> +    let scaleCheck;
Yo creo que no es necesario darle un valor al principio, pero tampoco estoy seguro.

2021-04-08 13:07 UTC, davzlum commented on davidvazquez/Precurso/airlines/airlines_pro.js
> +        return insertName();
Sí, es mejor así, en los proyectos anteriores ya empecé a usar el while

2021-04-08 13:09 UTC, davzlum commented on davidvazquez/Precurso/airlines/airlines_pro.js
> +    parseInt(price)
No me acuerdo, creo que se guarda en el propio price

2021-04-08 13:18 UTC, davzlum commented on davidvazquez/calculadora/calculadora.js
> +      outputResults.push('La raiz cuadrada de ' + num1 + ' es igual a ' + raiz);
Tomo nota para la próxima. Gracias!

2021-04-08 13:24 UTC, SantiagoMC52 approved these changes
Increíble trabajo sigue así!

2021-04-08 13:27 UTC, Emerson-feral approved these changes

2021-04-08 13:29 UTC, dmartorell requested changes

2021-04-08 13:29 UTC, dmartorell commented on davidvazquez/Precurso/calculadora/calculadora.js
> +  calculadora (2,4);
Supongo que puedes quitar los ejemplos de ejecución.
calculadora(2,4), calculadora(3,6) ...

2021-04-08 13:31 UTC, davzlum commented on davidvazquez/Precurso/calculadora/calculadora.js
> +  calculadora (2,4);
Pues sí, podía quitarlos

2021-04-08 13:32 UTC, dmartorell approved these changes

2021-04-08 15:36 UTC, merged