Hosni marco challenge git
SkylabCoders/skylab-bootcamp-202104-bcn pull request #58
Opened 2021-04-07 22:54 UTC by HosniMaRu

2021-04-08 08:17 UTC, edalandete requested changes

2021-04-08 08:17 UTC, edalandete commented on Hosni/Precurso/AIRLINES/airlines-pro.js
> +        if(flights.length >= 15) {
Sabemos que la longitud máxima de los vuelos es 15 pero, que pasa si cambia la longitud máxima a 20? Tendrías que cambiar todos los sitios que has puesto el 15. 

Podrías hacer una const que fuera el número máimo de vuelos.

2021-04-08 08:17 UTC, edalandete commented on Hosni/Precurso/AIRLINES/airlines-pro.js
> +            if (flights[i].id == askId) {
Mejor utilizar la triple ===

2021-04-08 08:17 UTC, edalandete commented on Hosni/Precurso/AIRLINES/airlines-pro.js
> +    while(askDelete.toUpperCase() === 'SI' && flights.length > 0);
Mismo caso que añadir vuelos.

2021-04-08 08:17 UTC, edalandete commented on Hosni/Precurso/AIRLINES/airlines-pro.js
> +        if(flights[i].scale === true){
Deberías cambiar el sort por filter y devolver los precios que tengan el precio superior.
Estas usando el array de flights en vez del array higherThan que es el array que deberías recorrer

2021-04-08 08:17 UTC, edalandete commented on Hosni/Precurso/AIRLINES/airlines-pro.js
> +        if(flights[i].scale === true){
Mismo caso que higherThan.

2021-04-08 09:05 UTC, HosniMaRu commented on Hosni/Precurso/AIRLINES/airlines-pro.js
> +    while(userName === '') {
cambio el texto para que quede claro que hacer click en cancelar representa EXIT

2021-04-08 12:52 UTC, Emerson-feral commented on Hosni/Precurso/CALCULADORA/calculator-pro.js
> +                for (i in valores) {
En el for in el "i" no tiene let o const, cuando lo haces así la variable se quedará como global(var) lo q puede suceder un error se hay otro "i"

2021-04-08 18:14 UTC, HosniMaRu commented on Hosni/Precurso/AIRLINES/airlines-pro.js
> +            if (flights[i].id == askId) {
en este caso, recuerdo que no puse el estrictly compare porque lo que devuelve el prompt es un string numerico, no un numero. Me vi forzado a utilizar solo el ==

2021-04-08 18:32 UTC, SantiagoMC52 approved these changes

2021-04-08 18:40 UTC, gteixi submitted a review, later dismissed

2021-04-08 18:41 UTC, SantiagoMC52 approved these changes

2021-04-08 18:41 UTC, Emerson-feral submitted a review, later dismissed

2021-04-08 19:42 UTC, SantiagoMC52 approved these changes

2021-04-08 23:11 UTC, HosniMaRu reviewed
.

2021-04-09 06:57 UTC, Emerson-feral approved these changes

2021-04-09 07:38 UTC, gteixi approved these changes

2021-04-09 07:43 UTC, jasuarez21 approved these changes
buen trabajo hosni!

2021-04-09 08:13 UTC, albertmasats reviewed
Te he revisado lo que más me llama la atención.

2021-04-09 08:13 UTC, albertmasats commented on hosni-marco/Precurso/AIRLINES/airlines-pro.js
> +
One line break, not 2. :)

2021-04-09 08:13 UTC, albertmasats commented on hosni-marco/Precurso/CALCULADORA HTML/index.html
> +            ">
this tag is floating in the space :octocat:

2021-04-09 08:13 UTC, albertmasats commented on hosni-marco/Precurso/CALCULADORA/calculator-pro.js
> +
Espacios ;)

2021-04-09 08:35 UTC, albertmasats reviewed
:)

2021-04-09 08:35 UTC, albertmasats commented on hosni-marco/Precurso/AIRLINES/airlines-pro.js
> +const flightsLengthMax = 15;
If you can put const before let it's better. ;)

2021-04-09 09:26 UTC, edalandete approved these changes
All ok!

2021-04-09 11:04 UTC, merged