Challenge portfolio
SkylabCoders/skylab-bootcamp-202104-bcn pull request #63
Opened 2021-04-08 07:27 UTC by Emerson-feral

2021-04-09 07:44 UTC, cristian-bars submitted a review, later dismissed
Good job!

2021-04-09 07:46 UTC, ulldecorb reviewed
The Semantic HTML is well integrated.
God job

2021-04-09 07:46 UTC, ulldecorb commented on emerson-fernandes/precourse/challenge/semanthic-html/beekeeping-guide.html
> +
remove empty lines for clean code and better performance.

2021-04-09 07:46 UTC, ulldecorb commented on emerson-fernandes/precourse/challenge/semanthic-html/news.html
> +
Remember remove empty lines.

2021-04-09 07:53 UTC, davzlum requested changes

2021-04-09 07:53 UTC, davzlum commented on emerson-fernandes/precourse/challenge/semanthic-html/news.html
> +
Borrar salto de linea

2021-04-09 07:53 UTC, davzlum commented on emerson-fernandes/precourse/challenge/semanthic-html/beekeeping-guide.html
> +        <p>All content on this site is &copy; National Society for Bee Protection
falta poner el tag <small> dentro del <p>  del footer

2021-04-09 07:53 UTC, davzlum commented on emerson-fernandes/precourse/challenge-portfolio/portfolio.html
> +    <section>
especificar  un poco el contenido de cada sección a través de las clases

2021-04-09 08:19 UTC, dmartorell requested changes

2021-04-09 08:19 UTC, dmartorell commented on emerson-fernandes/precourse/challenge/semanthic-html/news.html
> +
Borrar salto de linea

2021-04-09 08:19 UTC, dmartorell commented on emerson-fernandes/precourse/challenge/semanthic-html/news.html
> +
Borrar salto de linea

2021-04-09 20:44 UTC, gteixi submitted a review, later dismissed

2021-04-13 21:59 UTC, gaxxrodri approved these changes

2021-04-15 09:23 UTC, IrenePerezAlonso approved these changes

2021-04-19 09:55 UTC, dmartorell commented on emerson-fernandes/challenge-portfolio/portfolio.html
> +        <h1>Lorem</h1>
No sé si lo entiendo bien, pero diría que los tags H1 y H2 deberían ir dentro de la SECTION.

2021-04-19 09:58 UTC, dmartorell requested changes

2021-04-19 09:58 UTC, dmartorell commented on emerson-fernandes/precourse/challenge-portfolio/portfolio.html
> +<!DOCTYPE html>
Este archivo portfolio.html está duplicado?

2021-04-20 07:52 UTC, gaxxrodri approved these changes

2021-04-20 09:07 UTC, closed without merging