gaspar-r-html-cv
SkylabCoders/skylab-bootcamp-202104-bcn pull request #65
Opened 2021-04-08 07:29 UTC by gaxxrodri

2021-04-08 13:45 UTC, gteixi approved these changes
Buen cv!

2021-04-09 07:48 UTC, jasuarez21 approved these changes
esto esta estupendendo, me dan ganas de contratarte

2021-04-09 08:03 UTC, cristian-bars approved these changes
Muy buen curriculum Gaspar

2021-04-09 08:03 UTC, davzlum requested changes

2021-04-09 08:03 UTC, davzlum commented on Gaspar-R/challenge/home-challenge-semantic-cv/cv-html.html
> +        <h1>Gaspar Rodriguez</h1>
podrías incluir algún tag para poner una imagen de perfil tuya

2021-04-09 08:03 UTC, davzlum commented on Gaspar-R/challenge/home-challenge-semantic-cv/cv-html.html
> +                </li>
Muy buena la experiencia! xD

2021-04-09 08:03 UTC, annasm07 approved these changes
me falta Facebook vicepresident pero todo genial 😂

2021-04-09 08:04 UTC, davzlum approved these changes

2021-04-09 08:04 UTC, merged