Emerson-fernandes/challenge-html
SkylabCoders/skylab-bootcamp-202104-bcn pull request #66
Opened 2021-04-08 07:49 UTC by Emerson-feral

2021-04-08 22:16 UTC, IsabelGomez87 approved these changes
ok!

2021-04-09 07:37 UTC, dmartorell requested changes

2021-04-09 07:37 UTC, dmartorell commented on emerson-fernandes/precourse/challenge/semanthic-html/news.html
> +
Sobran espacios aquí

2021-04-09 07:47 UTC, jasuarez21 submitted a review, later dismissed
ni neymar, ronaldinho y ronaldo, programan asi!

2021-04-09 07:50 UTC, annasm07 submitted a review, later dismissed

2021-04-09 08:25 UTC, CheCabeza submitted a review, later dismissed

2021-04-09 20:44 UTC, gteixi approved these changes

2021-04-12 14:29 UTC, ulldecorb reviewed
God job with sass, but a little mess with space.

2021-04-12 14:29 UTC, ulldecorb commented on emerson-fernandes/precourse/challenge/semanthic-html/styles/main.css
> +}
In css files, add line break after close each property for a good performance and better readability.

2021-04-12 14:29 UTC, ulldecorb commented on emerson-fernandes/precourse/challenge/semanthic-html/styles/main.css
> +}
Caution: Add line break when close a property across all the file.

2021-04-12 14:29 UTC, ulldecorb commented on emerson-fernandes/precourse/challenge/semanthic-html/styles/responsive-nav.css
> +  .nav-toggle:hover {
Respect tab's hierarchy and delete not necessary space at begin of .nav-toggle:hover, a.nav-toggle & a.nav-toggle:hover

2021-04-13 21:59 UTC, gaxxrodri approved these changes

2021-04-15 06:53 UTC, gteixi approved these changes

2021-04-15 07:19 UTC, cristian-bars approved these changes
Good job Emerson!

2021-04-15 09:23 UTC, IrenePerezAlonso approved these changes

2021-04-16 08:28 UTC, gaxxrodri approved these changes
💯

2021-04-20 08:03 UTC, IsabelGomez87 approved these changes

2021-04-20 08:07 UTC, ulldecorb approved these changes
Bom trabalho Emerson!!

2021-04-20 09:06 UTC, closed without merging