Challenge/hosni marco curriculum
SkylabCoders/skylab-bootcamp-202104-bcn pull request #92
Opened 2021-04-08 23:06 UTC by HosniMaRu

2021-04-09 05:48 UTC, dmartorell requested changes

2021-04-09 05:48 UTC, dmartorell commented on hosni-marco/challenge/curriculum.html
> +            <img class="image-presentation" src="foto_presentacion.jpg" alt="Hosni">
Yo metería el tag 'figure' para meter la imagen.

2021-04-09 05:48 UTC, dmartorell commented on hosni-marco/challenge/curriculum.html
> +            <section class="personal-data-content">
Yo creo (no estoy seguro) que esta section puedes quitarla y poner la foto, el H1 y la UL todo dentro de <section class="principal-content">. Así evitas hacer secciones dentro de secciones.

2021-04-09 05:48 UTC, dmartorell commented on hosni-marco/challenge/curriculum.html
> +            <section>
Aquí para evitar meter secciones dentro de secciones cambiaría el tag de las secciones interiores por varios 'article'.

2021-04-09 05:48 UTC, dmartorell commented on hosni-marco/challenge/style.css
> +.poersonal-data-list {
Ojo que esta clase se llama 'poersonal' y la anterior es 'personal'.  ;)

2021-04-09 07:07 UTC, dmartorell submitted a review, later dismissed
Hecho!

2021-04-09 07:49 UTC, jasuarez21 approved these changes
nice!

2021-04-09 08:16 UTC, JDSanchon submitted a review, later dismissed

2021-04-09 08:17 UTC, davzlum commented on hosni-marco/challenge/curriculum.html
> +
borrar saltos de línea

2021-04-09 08:17 UTC, davzlum commented on hosni-marco/challenge/curriculum.html
> +                    <li class="poersonal-data-list">linkedin</li>
tendrías que añadir linkedin y github dentro de un tag <a> para hacer hyperlink

2021-04-09 08:17 UTC, davzlum commented on hosni-marco/challenge/style.css
> +h2, h3, h4 {
hacer salto de línea entre estilos

2021-04-09 08:22 UTC, JDSanchon submitted a review, later dismissed

2021-04-09 08:25 UTC, JDSanchon submitted a review, later dismissed

2021-04-09 08:32 UTC, jasuarez21 submitted a review, later dismissed

2021-04-09 20:46 UTC, gteixi reviewed
Me gusta mucho! Solo he encontrado un espacio extra por el código pero por lo demás muy bien!!

2021-04-09 20:46 UTC, gteixi commented on hosni-marco/challenge/curriculum.html
> +
Borra este espacio!

2021-04-10 12:58 UTC, gteixi approved these changes
Perfecto Hosni!

2021-04-10 22:40 UTC, gaxxrodri approved these changes

2021-04-14 11:19 UTC, annasm07 approved these changes
bien hecho! :)

2021-04-14 11:21 UTC, jasuarez21 approved these changes
nice

2021-04-14 11:22 UTC, merged